name: 'Nim Compiler on Alpine'
description: 'Nim language with tools'
branding:
  icon: 'box'  
  color: 'yellow'
inputs:
  command:
    description: 'Command to run'
    required: true
    default: 'nimble build --nimcache:/tmp/.cache --nimbleDir:/tmp/.nimble --gcc.exe:gcc --gcc.linkerexe:gcc --passL:-static -d:release --opt:size -y'
runs:
  using: 'docker'
  image: 'docker://smartcoder/nim:v1.2'
